language: shell
git:
  depth: false
matrix:
  include:
  - name: Ubuntu 14.04
    os: linux
    dist: trusty
  - name: Ubuntu 16.04
    os: linux
    dist: xenial
  - name: OS X 10.12
    os: osx
    osx_image: xcode8.3
  - name: OS X 10.14
    os: osx
    osx_image: xcode10.2
script:
- if [[ "$(lsb_release -c -s)" == xenial ]]; then export NEED_DEPLOY=sure; fi; echo "NEED_DEPLOY = [$NEED_DEPLOY]"
- export DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0
- git branch
- git rev-parse --abbrev-ref HEAD
# - (time nvm install node; echo "node is $(node --version)"; echo "npm is $(npm --version)";) 
# - nvm use default system; echo "node is $(node --version)"
# - npm install yarn -g || true; echo "yarn is $(yarn --version)" || true
- echo TRAVIS_OS_NAME is "$TRAVIS_OS_NAME"
- rm "$(command -v node)" 2>/dev/null || true

- |
   export TIMEFORMAT='REAL TIME: %1lR'

- export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1; export DOTNET_CLI_TELEMETRY_OPTOUT=1;
  export CI=false

- sudo ls -la || true; apt-cache policy dotnet-sdk-2.2 || true; apt-cache search dotnet-sdk || true

- |
  # install pv
  echo "A. ruby is $(ruby --version)" || true; echo "gem is $(gem --version)" || true
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew install jq mysql-client  
  else
    sudo apt-get install jq pv mysql-client postgresql-client -y
    ruby --version || true; gem --version || true

    mysql --version
  fi;
  echo "B. ruby is $(ruby --version)" || true; echo "gem is $(gem --version)" || true
  # - time gem search dpl | grep  -E '^dpl' | sort || true;

- |
  # Install 5 MySQL Servers
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    export MYSQL_TEST_DB=W3Top MYSQL_ROOT_PASSWORD=pass
    url=https://raw.githubusercontent.com/devizer/glist/master/install-5-mysqls-for-tests-V2.sh; (wget -q -nv --no-check-certificate -O - $url 2>/dev/null || curl -skSL $url) | bash
  fi;

- |
  # Install 7 Postgres Servers
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    export POSTGRESQL_DB=W3Top POSTGRESQL_PASS=pass POSTGRESQL_USER=postgres WAIT_TIMEOUT=13
    url=https://raw.githubusercontent.com/devizer/glist/master/install-7-postres-for-tests.sh; (wget -q -nv --no-check-certificate -O - $url 2>/dev/null || curl -skSL $url) | bash
  fi;
  
- |
  # Install Build Tools
  url=https://raw.githubusercontent.com/devizer/glist/master/install-dotnet-and-nodejs.sh;
  (wget -q -nv --no-check-certificate -O - $url 2>/dev/null || curl -ksSL $url) |
  bash -s dotnet node pwsh

- pushd build; ./inject-git-info.ps1; popd; cat bintray.json || true
- dotnet restore /v:m
- |
  echo "MYSQL TESTs ON TRAVIS"
  time dotnet test --no-restore -c Release -v q # Test only sqlite provider on linux and osx
  if false || [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
    for port in {3307..3311}; do
      export MYSQL_TEST_CONNECTION="Server=localhost;Database=mysql;Port=$port;Uid=root;Pwd=pass;Connect Timeout=5;Pooling=false;"
      pushd Universe.Dashboard.DAL.Tests
      time dotnet test -c Release --no-build -v m
      popd
    done
  fi
  
- pushd Universe.W3Top/ClientApp; time yarn install; time yarn build; popd

- |
   time dotnet publish -c Release -f netcoreapp2.2 /p:DefineConstants="DUMPS" -o bin/service /v:m
  
- |
   # publish self-contained
   pushd Universe.W3Top
   # skipping as we use publish-public.sh
   # time dotnet publish -c Release /p:DefineConstants="DUMPS" -o bin/service2 --self-contained -r linux-x64 /v:m
   popd
  
- export SKIP_GIT_PUSH=true; sudo mkdir -p /transient-builds; sudo chown $(whoami) /transient-builds;
- bash publish-public.sh
- echo Current dir is $(pwd)
- ls -la /transient-builds/publish/KernelManagementLab/Universe.W3Top/bin || true
- |
  verFile=./build/AppGitInfo.json; ver=$(cat $verFile | jq -r ".Version");
  echo "VER is  $ver";
  mkdir -p public-bintray/$ver;
  cp /transient-builds/publish/KernelManagementLab/Universe.W3Top/bin/*.tar.gz* public-bintray/$ver/;
  cp build/AppGitInfo.json public-bintray/$ver/version.json
- cat bintray.json || true
- pwd; df -h; ls -la public-bintray/$ver

deploy:

  provider: bintray
  file: "bintray.json"
  user: "devizer"
  key:
    secure: ktXky+XuUVh3M+ZPi9W+I8n6HOfPA84MVXja/3u2vSzDExJQrTMkqW86GbgVIs//JSDgh6slFuQCj14c5MgQqc4nIfuv/UwqbEPHmRsd1bPIrfj+Lh6hNB/TIYibuYe7Fi1ULJhCkQlTGtl4pR93EFSK2jb1sK6SJX8HLAPr5lBiIsUfJddEZ7MxAvppXaekn/huKZqRs4hP2GVzYWjA83N8muqgQmm8/2TAxVNtTnRkEO2cFVYAyphEAJt5nEagaabIdUfQNZWlpCCxCREeSbsLXlYjn4chhDEzBnP4NEfhBujAtQDOiMvPG42ynyFIWwY0MqfmhqHyQiqMFX/jMmINIvLfINlsypJf9UTlAR80XXJNEC90KwJ+WI12j+iwLLd2ZoI7fCrBssREenJdOapav9uqfyWJlbaKwvEjvBk/+aDvabOkfEQMb/NIx5zhgiWpvuT7gDw+NarKu2yJzqWW9EsVYLlGrA57YybWVdZbrISmRuKSy3gLTn3ZYbZzX56kafGmzaWIhjLtv9jRJeZiH1zj8OWyDZpIoRMfWQDgxNQZPhDEk0vyRhp6Ty5EGmH7dKbsCkDFDqDSKWaFpfhyHhP3LeiOCI0/WS319ZKIoqePOAPEWhhTKftHeyYPW2ndUidady9UNXhmlNomihFMaW9DTlH4PCysKkrlrjY=
  # passphrase: "Optional. In case a passphrase is configured on Bintray and GPG signing is used"
  skip_cleanup: true # to upload artifacts created during the build
  on:
    condition: ($NEED_DEPLOY = sure) && ($TRAVIS_TEST_RESULT = 0)
