language: node_js
matrix:
  include:
  - name: Ubuntu 14.04
    os: linux
    dist: trusty
  - name: Ubuntu 16.04
    os: linux
    dist: xenial
  - name: OS X 10.12
    os: osx
    osx_image: xcode8.3
  - name: OS X 10.14
    os: osx
    osx_image: xcode10.2
script:
- 
- (time nvm install node; echo "node is $(node --version)"; echo "npm is $(npm --version); npm install yarn -g";
  echo "yarn is $(yarn --version)") || true
- echo TRAVIS_OS_NAME is "$TRAVIS_OS_NAME"
- rm "$(command -v node)" 2>/dev/null || true
- export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1; export DOTNET_CLI_TELEMETRY_OPTOUT=1;
  export CI=false
- sudo ls -la || true; apt-cache policy dotnet-sdk-2.2 || true; apt-cache search dotnet-sdk || true

- |
  # install pv
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew install pv jq
  else
    sudo apt-get install jq pv -y
  fi;

- |
  # Install Build Tools
  url=https://raw.githubusercontent.com/devizer/glist/master/install-dotnet-and-nodejs.sh;
  (wget -q -nv --no-check-certificate -O - $url 2>/dev/null || curl -ksSL $url) |
  bash -s dotnet node pwsh

- dotnet restore /v:m
- time dotnet test
- pushd Universe.W3Top/ClientApp; time yarn install; popd
- time dotnet publish -c Release /p:DefineConstants="DUMPS" -o bin/service /v:m

- |
   # publish self-contained
   pushd Universe.W3Top
   # time dotnet publish -c Release /p:DefineConstants="DUMPS" -o bin/service2 --self-contained -r linux-x64 /v:m
   popd
  
- export SKIP_GIT_PUSH=true; sudo mkdir -p /transient-builds; sudo chown $(whoami) /transient-builds;
- bash publish-public.sh
- echo Current dir is $(pwd)
- ls -la /transient-builds/publish/KernelManagementLab/Universe.W3Top/bin || true
- mkdir -p public; cp /transient-builds/publish/KernelManagementLab/Universe.W3Top/bin/*.tar.gz public/

deploy:

  provider: bintray
  file: "bintray.json"
  user: "devizer"
  key:
    secure: ktXky+XuUVh3M+ZPi9W+I8n6HOfPA84MVXja/3u2vSzDExJQrTMkqW86GbgVIs//JSDgh6slFuQCj14c5MgQqc4nIfuv/UwqbEPHmRsd1bPIrfj+Lh6hNB/TIYibuYe7Fi1ULJhCkQlTGtl4pR93EFSK2jb1sK6SJX8HLAPr5lBiIsUfJddEZ7MxAvppXaekn/huKZqRs4hP2GVzYWjA83N8muqgQmm8/2TAxVNtTnRkEO2cFVYAyphEAJt5nEagaabIdUfQNZWlpCCxCREeSbsLXlYjn4chhDEzBnP4NEfhBujAtQDOiMvPG42ynyFIWwY0MqfmhqHyQiqMFX/jMmINIvLfINlsypJf9UTlAR80XXJNEC90KwJ+WI12j+iwLLd2ZoI7fCrBssREenJdOapav9uqfyWJlbaKwvEjvBk/+aDvabOkfEQMb/NIx5zhgiWpvuT7gDw+NarKu2yJzqWW9EsVYLlGrA57YybWVdZbrISmRuKSy3gLTn3ZYbZzX56kafGmzaWIhjLtv9jRJeZiH1zj8OWyDZpIoRMfWQDgxNQZPhDEk0vyRhp6Ty5EGmH7dKbsCkDFDqDSKWaFpfhyHhP3LeiOCI0/WS319ZKIoqePOAPEWhhTKftHeyYPW2ndUidady9UNXhmlNomihFMaW9DTlH4PCysKkrlrjY=
  # passphrase: "Optional. In case a passphrase is configured on Bintray and GPG signing is used"
  skip_cleanup: true # to upload artifacts created during the build

