language: minimal
matrix:
  include:
    - name: "Ubuntu 14.04"
      os: linux
      dist: trusty
    - name: "Ubuntu 16.04"
      os: linux
      dist: xenial
    - name: "OS X"
      os: osx
      osx_image: xcode7.2

script:
 - 'file=$(command -v node); if [ ! -z "$file" ]; then echo "Deleting node $(node --version): [$file]"; sudo rm $file; fi || true'
 - export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1; export DOTNET_CLI_TELEMETRY_OPTOUT=1; export CI=false
 - sudo ls -la
 - apt-cache policy dotnet-sdk-2.2 || true
 - apt-cache search dotnet-sdk || true
 - url=https://raw.githubusercontent.com/devizer/glist/master/install-dotnet-and-nodejs.sh; (wget -q -nv --no-check-certificate -O - $url 2>/dev/null || curl -ksSL $url) | bash -s dotnet node pwsh
 - dotnet restore
 - pushd Universe.W3Top/ClientApp; time yarn install; popd
 - time dotnet publish -c Release /p:DefineConstants="DUMPS" -o bin/service --self-contained -r linux-x64 /v:m
