variables:
    buildConfiguration: "Release"
    solution: "KernelManagementLab.sln"

jobs:

  - job: VM_Arm32_Bullseye_6_20
    variables:
      OS: Linux
      VM_KEY: ARMv7-Bullseye
      QEMU_VER: 6.2.0
    timeoutInMinutes: 180
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
      - template: azure-steps-vm.yml

  - job: VM_Arm32_Bullseye_5_2
    variables:
      OS: Linux
      VM_KEY: ARMv7-Bullseye
      QEMU_VER: 5.2.0
    timeoutInMinutes: 180
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
      - template: azure-steps-vm.yml

  - job: VM_Arm32_Bullseye_4_2
    variables:
      OS: Linux
      VM_KEY: ARMv7-Bullseye
      QEMU_VER: 4.2.0
    timeoutInMinutes: 180
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
      - template: azure-steps-vm.yml

  # - job: VM_Arm32_Bullseye_1Core
  #   variables:
  #     OS: Linux
  #     VM_KEY: ARMv7-Bullseye
  #     VM_CPUS: 1
  #   timeoutInMinutes: 180
  #   cancelTimeoutInMinutes: 1
  #   pool:
  #     vmImage: 'ubuntu-20.04'
  #   steps:
  #     - template: azure-steps-vm.yml

  - job: VM_Arm32_Stretch
    variables:
      OS: Linux
      VM_KEY: ARMv7-Stretch
      # QEMU_VER: 6.2.0
    timeoutInMinutes: 180
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - template: azure-steps-vm.yml

  # - job: VM_Arm32_Stretch_1Core
  #   variables:
  #     OS: Linux
  #     VM_KEY: ARMv7-Stretch
  #     VM_CPUS: 1
  #     # QEMU_VER: 6.2.0
  #   timeoutInMinutes: 180
  #   cancelTimeoutInMinutes: 1
  #   pool:
  #     vmImage: 'ubuntu-18.04'
  #   steps:
  #     - template: azure-steps-vm.yml

  # - job: VM_Arm32_Buster
  #   variables:
  #     OS: Linux
  #     VM_KEY: ARMv7
  #     QEMU_VER: 6.2.0
  #   timeoutInMinutes: 360
  #   cancelTimeoutInMinutes: 1
  #   pool:
  #     vmImage: 'ubuntu-20.04'
  #   steps:
  #     - template: azure-steps-vm.yml

  - job: VM_Arm64_Buster
    variables:
      OS: Linux
      VM_KEY: ARMv8
    timeoutInMinutes: 180
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
      - template: azure-steps-vm.yml

  # - job: Arm32
  #   variables:
  #     OS: Linux
  #   timeoutInMinutes: 360
  #   cancelTimeoutInMinutes: 1
  #   pool:
  #     name: 'armv7-pool'
  #   steps:
  #     - template: azure-steps-nix.yml

  # - job: Arm64
  #   variables:
  #     OS: Linux
  #   timeoutInMinutes: 360
  #   cancelTimeoutInMinutes: 1
  #   pool:
  #     name: 'arm64-pool'
  #   steps:
  #     - template: azure-steps-nix.yml

  - job: Ubuntu_20_04
    variables:
      OS: Linux
    timeoutInMinutes: 99
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
      - template: azure-steps-nix.yml

  - job: Ubuntu_18_04
    variables:
      OS: Linux
    timeoutInMinutes: 99
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - template: azure-steps-nix.yml

  # needs explicit dotnet core installation
  - job: MacOS_10_14
    variables:
      OS: OSX
    timeoutInMinutes: 99
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'macOS-10.14'
    steps:
      - template: azure-steps-nix.yml

  - job: MacOS_10_15
    variables:
      OS: OSX
    timeoutInMinutes: 99
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'macOS-10.15'
    steps:
      - template: azure-steps-nix.yml

  - job: MacOS_11
    variables:
      OS: OSX
    timeoutInMinutes: 99
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'macOS-11'
    steps:
      - template: azure-steps-nix.yml

  - job: WIN2016_VS2017
    variables:
      OS: Windows
    timeoutInMinutes: 99
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - template: azure-steps-nix.yml

  - job: WIN2019_VS2019
    variables:
      OS: Windows
    timeoutInMinutes: 99
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'windows-2019'
    steps:
      - template: azure-steps-nix.yml

  - job: WIN2022
    variables:
      OS: Windows
    timeoutInMinutes: 99
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'windows-2022'
    steps:
      - template: azure-steps-nix.yml

trigger:
  - master

pr:
  branches:
    exclude:
      - '*'


