trigger:
- manual

pool:
  vmImage: 'ubuntu-20.04'
  
jobs:
- job: publish_w3top
  timeoutInMinutes: 100

  steps:
  - script: |
      set -eu;
      script=https://raw.githubusercontent.com/devizer/test-and-build/master/install-build-tools-bundle.sh; (wget -q -nv --no-check-certificate -O - $script 2>/dev/null || curl -ksSL $script) | bash >/dev/null
      Say --Reset-Stopwatch
      Say "apt"
      sudo apt-get update -qq;
      sudo apt-get install sshpass rsync openjdk-11-jdk tree git ruby-dev p7zip-full pv jq -y -qq | { grep "Setting\|Unpack" || true; }
      Say "dpl"
      sudo gem install dpl dpl-releases
      Say "/transient-builds"
      sudo mkdir -p /transient-builds
      sudo chown -R $(whoami) /transient-builds
      Say "push token"
      mkdir -p ~/.ssh; cd ~/.ssh
      urll="https://master.dl.sourceforge.net/project/fio/build-matrix/build-server.fingerprint?viasf=1"
      curl -kSL -o build-server.fingerprint "$urll"
      7z x -p${GITHUB_PUSH_TOKEN} -t7z -y build-server.fingerprint
      Say "Provisioning completed"
    displayName: 'Provisioning'
    env:
      GITHUB_PUSH_TOKEN: $(SECRET_ID1)
  
  - script: |
      set -eu;
      git config --global user.email "devizer@github.io"
      git config --global user.name "devizer"
      export GITHUB_RELEASE_TOKEN;
      bash -eu publish-public.sh

      Say "Deploying sf.net release"
      sshpass -p "${SF_TOKEN}" rsync -r /transient-builds/w3top-new-version-for-sf/. archivarius@frs.sourceforge.net:/home/frs/p/w3top/

      Say "Pack /transient-builds"
      7z a -mx=1 -ms=on -mqs=on $SYSTEM_ARTIFACTSDIRECTORY/transient-builds.7z /transient-builds
      Say "Pack ${BUILD_SOURCESDIRECTORY}"
      7z a -mx=1 -ms=on -mqs=on $SYSTEM_ARTIFACTSDIRECTORY/Sources-Directory.7z ${BUILD_SOURCESDIRECTORY}
      ls -la $SYSTEM_ARTIFACTSDIRECTORY
    displayName: 'Publish W3Top'
    env:
      GITHUB_RELEASE_TOKEN: $(SECRET_ID2)
      SF_TOKEN: $(SECRET_ID3)

  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()
    displayName: 'Drop Transient Builds'
    inputs:
      pathtoPublish: '$(System.ARTIFACTSDIRECTORY)'
      artifactName: '$(Agent.JobName)'
