# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
  - job: Build
    timeoutInMinutes: 599
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-latest'
    
    steps:

      - script: |
          pushd fio.lab
          export CFLAGS="-O2"
          export CXXFLAGS="-O2"
          bash rebuild-all.sh
          popd
        displayName: 'rebuild all'

      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: 'fio.lab/result'
          artifactName: fio
