# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
  - job: Build
    timeoutInMinutes: 599
    cancelTimeoutInMinutes: 3
    pool:
      vmImage: 'ubuntu-latest'
    
    steps:

      - script: |
          pushd fio.lab
          mkdir -p result; rm -rf result/* || true
          bash rebuild-all.sh | tee result/detailed.log
          popd
        displayName: 'rebuild all'

      - task: PublishBuildArtifacts@1
        condition: succeededOrFailed()
        inputs:
          pathToPublish: 'fio.lab/result'
          artifactName: fio
