using System;
using System.Linq;

namespace AutoGeneratedTests
{
    public partial class FioParserTestCase {
        public override string ToString()
        {
            return $"fio-{Version}";
        }

        static FioParserTestCase()
        {
            var sorted = All.OrderBy(x => new Version(x.Version));
            All = sorted.ToArray();
        }
    }
}