using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace AutoGeneratedTests
{
    public class FioParserTestCase2
    {
        public int NumJobs;
        public string Version;
        public string Method;
        public string[] Lines;

        public override string ToString()
        {
            return $"{Version}: {(NumJobs > 1 ? NumJobs + " jobs *" : "")} {Method}, {Lines.Length} lines";
        }

        public static IEnumerable<FioParserTestCase2> GetAll_V3()
        {
            var all = GetAll_V3_Impl().ToArray();
            var sorted = all.OrderBy(x => new Version(x.Version)).ToArray();
            return sorted;
        }

        static IEnumerable<FioParserTestCase2> GetAll_V3_Impl()
        {
            var methods = new[]
            {
                new {Name = "Seq Read", File = "read.log"},
                new {Name = "Seq Write", File = "write.log"},
                new {Name = "Rand Read", File = "randread.log"},
                new {Name = "Rand Write", File = "randwrite.log"},
            };
            
            var numjobs_dirs = new DirectoryInfo("fio-test-cases").GetDirectories();
            foreach (var numjobs_dir in numjobs_dirs)
            {
                var numjobs_dir_name = numjobs_dir.Name;
                Console.WriteLine($"numjobs_dir_name: {numjobs_dir_name}");
                var numJobs = int.Parse(numjobs_dir_name.Split('-').First());
                var fio_dirs = new DirectoryInfo(numjobs_dir.FullName).GetDirectories();
                foreach (DirectoryInfo dir in fio_dirs)
                {
                    var version = dir.Name;
                    foreach (var method in methods)
                    {
                        var file = Path.Combine(dir.FullName, method.File);
                        if (!File.Exists(file))
                        {
                            Console.WriteLine($"WARNING: TEST CASE MISSING: {file}");
                            continue;
                        }
                        var lines = ReadLines(file);
                        yield return new FioParserTestCase2()
                        {
                            NumJobs = numJobs,
                            Lines = lines,
                            Method = method.Name,
                            Version = TryParseVersion(version),
                        };
                    }
                }
                
            }

        }

        static string TryParseVersion(string raw)
        {
            if (raw.Length >= 5)
            {
                if (raw.StartsWith("fio-", StringComparison.OrdinalIgnoreCase))
                    raw = raw.Substring(4);
                if (raw.StartsWith("fio ", StringComparison.OrdinalIgnoreCase))
                    raw = raw.Substring(4);
            }

            return raw;
        }

        static string[] ReadLines(string fileName)
        {
            using(FileStream fs = new FileStream(fileName, FileMode.Open, FileAccess.Read, FileShare.ReadWrite, 32768))
            using (StreamReader rdr = new StreamReader(fs, new UTF8Encoding(false)))
            {
                var all = rdr.ReadToEnd();
                return all.Split(new[] {'\n', '\r'}, StringSplitOptions.RemoveEmptyEntries);
            }
        }

        public static IEnumerable<FioParserTestCase2> GetAll()
        {
            foreach (var testCase in FioParserTestCase.All)
            {
                var methods = new[]
                {
                    new {Name = "Seq Read", Lines = testCase.SeqRead},
                    new {Name = "Seq Write", Lines = testCase.SeqWrite},
                    new {Name = "Rand Read", Lines = testCase.RandRead},
                    new {Name = "Rand Write", Lines = testCase.RandWrite},
                };
                foreach (var method in methods)
                {
                    yield return new FioParserTestCase2()
                    {
                        Version = testCase.Version,
                        Method = method.Name,
                        Lines = method.Lines,
                    };
                }
            }
        } 
    }
}