using System;
using AutoGeneratedTests;
using NUnit.Framework;
using Tests;

namespace Universe.FioStream.Tests
{
    public class TestAll : NUnitTestsBase
    {
        [SetUp]
        public void Setup()
        {
        }

        [Test]
        public void _0_Info()
        {
            Console.WriteLine($"FioParserTestCase.All.Length: {FioParserTestCase.All.Length}");
            Assert.Pass();
        }
        
        [Test, TestCaseSource(typeof(FioParserTestCase), nameof(FioParserTestCase.All))]
        public void _1_All(FioParserTestCase testCase)
        {
            var methods = new[]
            {
                new {Name = "SeqRead", Lines = testCase.SeqRead},
                new {Name = "SeqWrite", Lines = testCase.SeqWrite},
                new {Name = "RandRead", Lines = testCase.RandRead},
                new {Name = "RandRead", Lines = testCase.RandWrite},
            };
            foreach (var method in methods)
            {
                FioStreamReader reader = new FioStreamReader();
                foreach (var line in method.Lines)
                {
                    reader.ReadNextLine(line);
                }
            }
        }

    }
}