using System;
using AutoGeneratedTests;
using NUnit.Framework;
using Tests;

namespace Universe.FioStream.Tests
{
    public class TestAll : NUnitTestsBase
    {
        [SetUp]
        public void Setup()
        {
        }

        [Test]
        public void _0_Info()
        {
            Console.WriteLine($"FioParserTestCase.All.Length: {FioParserTestCase.All.Length}");
            Assert.Pass();
        }

        [Test, TestCaseSource(typeof(FioParserTestCase2), nameof(FioParserTestCase2.GetAll))]
        public void _1_All(FioParserTestCase2 testCase)
        {
            JobSummaryResult jobSummaryResult = null;
            FioStreamReader reader = new FioStreamReader();
            reader.NotifyJobSummary += result =>
            {
                Console.WriteLine($"JobSummaryResult: {result}");
                jobSummaryResult = result;
            };

            reader.NotifyEta += eta =>
            {
                Console.WriteLine($"ETA: {eta}");
            };

            bool isFirst = true;
            reader.NotifyJobProgress += jobProgress =>
            {
                Console.WriteLine($"JobProgress: {jobProgress}");
                Assert.IsTrue(jobProgress.Eta.HasValue, "ETA is not null");
                Assert.IsTrue(jobProgress.PerCents.HasValue, "PerCents is not null");
                Assert.IsTrue(jobProgress.PerCents.Value > 0, "PerCents bigger then zero");
                if (!isFirst)
                {
                    Assert.IsTrue(
                        jobProgress.ReadIops.GetValueOrDefault() > 0 || jobProgress.WriteIops.GetValueOrDefault() > 0,
                        "Either Read IOPS or Write IOPS bigger then zero");
                }

                isFirst = false;
            };
            
            foreach (var line in testCase.Lines)
            {
                reader.ReadNextLine(line);
            }
            
            Assert.NotNull(jobSummaryResult, "FioStreamReader should provide JobSummaryResult");
            Assert.True(jobSummaryResult.Iops > 0, "JobSummaryResult.Iops should be greater then zero");
            Assert.True(jobSummaryResult.Bandwidth > 0, "JobSummaryResult.Bandwidth should be greater then zero");
        }

    }
}