using System;
using AutoGeneratedTests;
using NUnit.Framework;
using Tests;

namespace Universe.FioStream.Tests
{
    public class TestAll : NUnitTestsBase
    {
        [SetUp]
        public void Setup()
        {
        }

        [Test]
        public void _0_Info()
        {
            Console.WriteLine($"FioParserTestCase.All.Length: {FioParserTestCase.All.Length}");
            Assert.Pass();
        }

        [Test, TestCaseSource(typeof(FioParserTestCase2), nameof(FioParserTestCase2.GetAll))]
        public void _1_All(FioParserTestCase2 testCase)
        {
            FioStreamReader.JobSummaryResult jobSummaryResult = null;
            FioStreamReader reader = new FioStreamReader();
            reader.NotifyJobSummary += result =>
            {
                Console.WriteLine($"JobSummaryResult: {result}");
                jobSummaryResult = result;
            };
            
            foreach (var line in testCase.Lines)
            {
                reader.ReadNextLine(line);
            }
            
            Assert.NotNull(jobSummaryResult, "FioStreamReader should provide JobSummaryResult");
            Assert.True(jobSummaryResult.Iops > 0, "JobSummaryResult.Iops should be greater then zero");
            Assert.True(jobSummaryResult.Bandwidth > 0, "JobSummaryResult.Bandwidth should be greater then zero");
        }

    }
}