// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Universe.Dashboard.DAL;

namespace Universe.Dashboard.DAL.MySQL.Migrations
{
    [DbContext(typeof(DashboardContext))]
    [Migration("20220626040820_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Universe.Dashboard.DAL.DbInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .HasColumnType("VARCHAR(20000)");

                    b.HasKey("Id");

                    b.ToTable("DbInfo");
                });

            modelBuilder.Entity("Universe.Dashboard.DAL.DiskBenchmarkEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Args")
                        .HasColumnType("LONGTEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("ErrorInfo")
                        .HasColumnType("text");

                    b.Property<string>("MountPath")
                        .HasColumnType("VARCHAR(20000)");

                    b.Property<string>("Report")
                        .HasColumnType("LONGTEXT");

                    b.Property<string>("Token")
                        .HasColumnType("VARCHAR(36)");

                    b.HasKey("Id");

                    b.ToTable("DiskBenchmark");
                });

            modelBuilder.Entity("Universe.Dashboard.DAL.HistoryCopy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("JsonBlob")
                        .HasColumnType("LONGTEXT");

                    b.Property<string>("Key")
                        .HasColumnType("VARCHAR(20000)");

                    b.HasKey("Id");

                    b.ToTable("HistoryCopy");
                });
#pragma warning restore 612, 618
        }
    }
}
