using System;
using System.Collections.Generic;
using System.Linq;
using AutoGeneratedTests;
using Universe.FioStream.Tests;

namespace Universe.FioStream.Profiler
{
    class Program
    {
        static void Main(string[] args)
        {
            FioStreamReaderTests tst = new FioStreamReaderTests();
            FioParserTestCase2[] tests = FioParserTestCase2.GetAll_V3().ToArray();
            tst.FullFio(tests.First());
            Console.WriteLine($"Starting FioStreamReaderTests: {tests.Length} cases");
            Console.ReadLine();
            foreach (var test in tests)
            {
                tst.FullFio(test);
            }
            Console.WriteLine($"Completed FioStreamReaderTests: {tests.Length} cases");
            Console.ReadLine();
        }
    }
}